package com.capgemini.university.dao;

public interface QueryMapper {
	public static String CHECK_LOGIN_QUERY="SELECT * FROM USERS WHERE LOGIN_ID=? AND PASSWORD=?";
	public static String INSERT_PROGRAM="INSERT INTO PROGRAMS_OFFERED VALUES (?,?,?,?,?)";
	public static String INSERT_SCHEDULE="INSERT INTO PROGRAMS_SCHEDULED VALUES (?,?,?,TO_DATE(?,'DD/MM/YYYY'),TO_DATE(?,'DD/MM/YYYY'),?)";
	public static String VIEW_PROGRAMS_OFFERED="SELECT * FROM PROGRAMS_OFFERED";
	public static String VIEW_SCHEDULE="SELECT * FROM PROGRAMS_SCHEDULED";
	public static String DELETE_PROGRAM="DELETE FROM PROGRAMS_OFFERED WHERE PROGRAMNAME=?";
	public static String DELETE_SCHEDULE="DELETE FROM PROGRAMS_SCHEDULED WHERE SCHEDULED_PROGRAM_ID=?";
	public static String SCHEDULES_BETWEEN_TIME_INTERVAL="SELECT * FROM PROGRAMS_SCHEDULED WHERE START_DATE BETWEEN TO_DATE(?, 'DD/MM/YYYY') AND TO_DATE(?, 'DD/MM/YYYY')";
	public static String SCHEDULE_APPLICANT_STATUS="SELECT * FROM APPLICATION WHERE SCHEDULED_PROGRAM_ID=?";
	public static String INSERT_APPLICATION = "INSERT INTO APPLICATION VALUES (?,?,TO_DATE(?,'dd/MM/yyyy'),?,?,?,?,?,?,TO_DATE(?,'dd/MM/yyyy'))";
	public static String DISPLAY_APPLICATION_STATUS = "SELECT STATUS FROM APPLICATION WHERE APPLICATION_ID=?";
	public static String VIEW_APPLICATIONS = "SELECT * FROM APPLICATION A JOIN PROGRAMS_SCHEDULED P ON A.SCHEDULED_PROGRAM_ID=P.SCHEDULED_PROGRAM_ID WHERE PROGRAMNAME=?";
	public static String UPDATE_INTERVIEW_STATUS = "UPDATE APPLICATION SET DATE_OF_INTERVIEW=TO_DATE(?,'dd/MM/yyyy'),STATUS='APPROVED' WHERE APPLICATION_ID=?";
	public static String VIEW_NEW_APPLICATIONS = "SELECT * FROM APPLICATION WHERE STATUS='APPLIED'";
	public static String UPDATE_REJECT_STATUS = "UPDATE APPLICATION SET STATUS='REJECTED' WHERE APPLICATION_ID=?";
	public static String VIEW_APPROVED_APPLICATIONS = "SELECT * FROM APPLICATION WHERE STATUS='APPROVED'";
	public static String UPDATE_CONFIRM_STATUS = "UPDATE APPLICATION SET STATUS='CONFIRMED' WHERE APPLICATION_ID=?";
}
